version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0.23
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev-moveshop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3320:3306"
