version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0.23
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev-moveshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
